"""
Generate Modelfile.yuzu and (optionally) register it with Ollama.

The Modelfile is GENERATED, never hand-edited. Yuzu's personality lives
in exactly one place -- yuzu_system_prompt.txt -- and this stamps it
into the Modelfile alongside the sampling settings from yuzu_brain.py.
Edit the prompt, re-run this, and the code and the model agree. That's
the fix for the same personality text existing in four files and
quietly diverging.

    python build_yuzu_model.py                 # write Modelfile.yuzu
    python build_yuzu_model.py --create        # ...and ollama create yuzu
    python build_yuzu_model.py --base ./Llama-3.2-3B-heretic-Q4_K_M.gguf
"""

import subprocess
import sys
from pathlib import Path

from yuzu_brain import DEFAULT_OPTIONS, load_system_prompt

HERE = Path(__file__).parent
MODELFILE = HERE / "Modelfile.yuzu"

# The base weights. Three ways to fill this in, in order of preference:
#
#  1. A local GGUF you downloaded or converted:
#         FROM ./Llama-3.2-3B-Instruct-heretic-Q4_K_M.gguf
#  2. Ollama pulling a GGUF repo straight from Hugging Face:
#         FROM hf.co/<user>/<repo>:Q4_K_M
#     (only works if that repo actually contains GGUF files)
#  3. Stock Llama 3.2 3B, to get the pipeline working before the
#     abliterated weights are sorted out:
#         FROM llama3.2:3b
#
# Default is stock, so `--create` works on day one without a download.
DEFAULT_BASE = "llama3.2:3b"

# Ollama's Modelfile takes a subset of what the API accepts; num_ctx and
# num_predict belong here too, the rest map straight across.
MODELFILE_PARAMS = ("temperature", "top_p", "top_k", "min_p",
                    "repeat_penalty", "num_predict", "num_ctx")


def render(base=DEFAULT_BASE, options=None):
    options = dict(DEFAULT_OPTIONS, **(options or {}))
    lines = [
        "# GENERATED by build_yuzu_model.py -- do not edit by hand.",
        "# Personality: yuzu_system_prompt.txt   Sampling: yuzu_brain.py",
        "",
        f"FROM {base}",
        "",
    ]
    for key in MODELFILE_PARAMS:
        if key in options:
            lines.append(f"PARAMETER {key} {options[key]}")
    lines += [
        "",
        '# Stop before the model starts writing the user\'s turn for her.',
        '# Directive 4 (NO PUPPETEERING) is a prompt rule; this enforces it',
        '# at the decoder, which a 3B respects a lot more reliably.',
        'PARAMETER stop "User:"',
        'PARAMETER stop "\\nYou:"',
        "",
        'SYSTEM """',
        load_system_prompt(),
        '"""',
        "",
    ]
    return "\n".join(lines)


def main(argv):
    base = DEFAULT_BASE
    create = False
    args = list(argv)
    while args:
        arg = args.pop(0)
        if arg == "--base" and args:
            base = args.pop(0)
        elif arg == "--create":
            create = True
        elif arg in ("-h", "--help"):
            print(__doc__)
            return 0

    MODELFILE.write_text(render(base), encoding="utf-8")
    print(f"Wrote {MODELFILE.name}  (FROM {base})")

    if not create:
        print("Register it with:  ollama create yuzu -f Modelfile.yuzu")
        return 0

    print("Running: ollama create yuzu -f Modelfile.yuzu")
    try:
        result = subprocess.run(
            ["ollama", "create", "yuzu", "-f", str(MODELFILE)],
            cwd=HERE, check=False,
        )
    except FileNotFoundError:
        print("ollama isn't on PATH. Install it first -- see JETSON_SETUP.md")
        return 1
    if result.returncode == 0:
        print("\nDone. Try her out:  python yuzu_brain.py --chat")
    return result.returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
