"""
Generate a Modelfile per persona and (optionally) register it with
Ollama, so each character is its own model you can switch between:

    ollama run yuzu      # gyaru
    ollama run saya      # tsundere
    ollama run coco      # kuudere

Modelfiles are GENERATED, never hand-edited. A persona's personality
lives in exactly one place -- personas/<key>.persona -- and this stamps
it into the Modelfile with that persona's sampling settings. Edit the
persona, re-run this, and the code and the model agree.

    python build_yuzu_model.py                    # Modelfile.yuzu
    python build_yuzu_model.py --create           # ...and ollama create
    python build_yuzu_model.py --persona saya --create
    python build_yuzu_model.py --all --create     # every persona at once
    python build_yuzu_model.py --base ./model-Q4_K_M.gguf --create
"""

import subprocess
import sys
from pathlib import Path

import yuzu_personas
from yuzu_brain import DEFAULT_OPTIONS

HERE = Path(__file__).parent

# The base weights. Three ways to fill this in, in order of preference:
#
#  1. A local GGUF you downloaded or converted:
#         FROM ./Llama-3.2-3B-Instruct-heretic-Q4_K_M.gguf
#  2. Ollama pulling a GGUF repo straight from Hugging Face:
#         FROM hf.co/<user>/<repo>:Q4_K_M
#     (only works if that repo actually contains GGUF files)
#  3. Stock Llama 3.2 3B, to get the pipeline working before the
#     abliterated weights are sorted out:
#         FROM llama3.2:3b
#
# Default is stock, so `--create` works on day one without a download.
DEFAULT_BASE = "llama3.2:3b"

# Ollama's Modelfile takes a subset of what the API accepts; num_ctx and
# num_predict belong here too, the rest map straight across.
MODELFILE_PARAMS = ("temperature", "top_p", "top_k", "min_p",
                    "repeat_penalty", "num_predict", "num_ctx")


def modelfile_path(persona_key):
    return HERE / f"Modelfile.{persona_key}"


def render(base=DEFAULT_BASE, options=None, persona_key=yuzu_personas.DEFAULT_PERSONA):
    persona = yuzu_personas.load(persona_key)
    # Precedence: explicit options > persona settings > defaults.
    # Layered, not dict(a, **b, **c) -- that raises whenever two layers
    # set the same key, i.e. exactly when overriding.
    merged = dict(DEFAULT_OPTIONS)
    merged.update(persona.options())
    merged.update(options or {})
    options = merged
    lines = [
        "# GENERATED by build_yuzu_model.py -- do not edit by hand.",
        f"# Persona: personas/{persona_key}.persona "
        f"({persona.name}, {persona.archetype})",
        f"# Body:    personas/_hardware_{persona.hardware}.txt",
        "",
        f"FROM {base}",
        "",
    ]
    for key in MODELFILE_PARAMS:
        if key in options:
            lines.append(f"PARAMETER {key} {options[key]}")
    lines += [
        "",
        '# Stop before the model starts writing the user\'s turn for her.',
        '# Directive 4 (NO PUPPETEERING) is a prompt rule; this enforces it',
        '# at the decoder, which a 3B respects a lot more reliably.',
        'PARAMETER stop "User:"',
        'PARAMETER stop "\\nYou:"',
        "",
        'SYSTEM """',
        persona.prompt,
        '"""',
        "",
    ]
    return "\n".join(lines)


def build_one(persona_key, base, create):
    path = modelfile_path(persona_key)
    path.write_text(render(base, persona_key=persona_key), encoding="utf-8")
    print(f"Wrote {path.name}  (persona {persona_key}, FROM {base})")

    if not create:
        print(f"  Register:  ollama create {persona_key} -f {path.name}")
        return 0
    try:
        result = subprocess.run(
            ["ollama", "create", persona_key, "-f", str(path)],
            cwd=HERE, check=False,
        )
    except FileNotFoundError:
        print("  ollama isn't on PATH. Install it -- see JETSON_SETUP.md")
        return 1
    if result.returncode == 0:
        print(f"  Created model '{persona_key}'. Try: "
              f"python yuzu_brain.py --persona {persona_key} --chat")
    return result.returncode


def main(argv):
    base = DEFAULT_BASE
    create = False
    every = False
    persona_key = yuzu_personas.DEFAULT_PERSONA
    args = list(argv)
    while args:
        arg = args.pop(0)
        if arg == "--base" and args:
            base = args.pop(0)
        elif arg == "--persona" and args:
            persona_key = args.pop(0).lower()
        elif arg == "--all":
            every = True
        elif arg == "--create":
            create = True
        elif arg in ("-h", "--help"):
            print(__doc__)
            return 0

    keys = yuzu_personas.available() if every else [persona_key]
    failures = 0
    for key in keys:
        try:
            failures += bool(build_one(key, base, create))
        except yuzu_personas.PersonaError as exc:
            print(f"\n{exc}\n")
            failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
