#!/usr/bin/env python3
"""Four's picture for the StackChan cube: ui/four/four.jpg -> four_art.h.

    python3 stackchan/make_art.py          rewrite four_cube/four_art.h

THE CUBE'S SCREEN IS 320x240, landscape, and Ghost picked layout B off a
mockup at that size (Oct 2): all of her, 160x240 down the middle, with
her code rain falling either side and through her dark side. So her art
is shrunk to 160x240 once, here, and baked into the firmware as RGB565
-- the screen's own pixel format -- so the cube decodes nothing at run
time and needs no image library.

GENERATED, AND COMMITTED ANYWAY, the Modelfile call: flashing the cube
must not need PIL on whatever machine does it, and a test regenerates
this into a temp file and compares, so the header cannot drift from her
art. Change her picture, run this, commit both.

WORKBENCH TOOL. PIL is needed here and nowhere else -- the deck never
imports this, same standing as yuzu_art.py.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE.parent / "ui" / "four" / "four.jpg"
OUT = HERE / "four_cube" / "four_art.h"
ART_W, ART_H = 160, 240


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def render(source=SOURCE):
    """The header's text. Same input, same bytes, every time."""
    from PIL import Image
    img = Image.open(source).convert("RGB").resize((ART_W, ART_H),
                                                     Image.LANCZOS)
    px = img.load()
    values = [rgb565(*px[x, y]) for y in range(ART_H) for x in range(ART_W)]
    lines = ["// GENERATED by stackchan/make_art.py from ui/four/four.jpg.",
             "// Do not edit -- change her picture and run the script.",
             "#pragma once",
             "#include <stdint.h>",
             "static const int FOUR_ART_W = %d, FOUR_ART_H = %d;"
             % (ART_W, ART_H),
             "// RGB565, row by row, as the colour (not byte-swapped).",
             "static const uint16_t FOUR_ART[%d] = {" % len(values)]
    for i in range(0, len(values), 16):
        lines.append("  " + ",".join("0x%04x" % v for v in values[i:i + 16])
                     + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    try:
        text = render()
    except ImportError:
        sys.exit("This needs PIL: pip install pillow. The committed "
                 "four_art.h already works; you only need this to change "
                 "her picture.")
    OUT.write_text(text)
    print("wrote %s (%d bytes)" % (OUT, len(text)))
