#!/usr/bin/env python3
"""The girls' pictures for the StackChan cube, baked into its program.

    python3 stackchan/make_art.py          rewrite cube/four_art.h,
                                           cube/yuzu_art.h and
                                           cube/zero_art.h

THE CUBE'S SCREEN IS 320x240, landscape, and Ghost picked layout B off a
mockup at that size (Oct 2): all of Four, 160x240 down the middle, with
her code rain falling either side and through her dark side. So her art
is shrunk to 160x240 once, here, and baked into the firmware as RGB565
-- the screen's own pixel format -- so the cube decodes nothing at run
time and needs no image library.

YUZU, THE SAME DAY ("Can you squeeze Yuzu on too?"), is her page's
portrait: ui/yuzu/yuzu.png, already cut out of its white, shrunk to
178x230 so she stands on the floor of the screen with the lavender room
either side of her. She keeps her ALPHA, which Four never needed (Four
is blended with `screen`, so black is her transparency): Yuzu sits on a
room, not on black. And her page's three fades are baked into that
alpha here, so the cube draws them for free -- the bottom 16% of the
bust and 9% at each sleeve, intersected (multiplied), exactly the CSS
mask on her page.

ZERO, LATER THE SAME DAY ("Can the qwen variant, Zero, go on there
plz?"), is her page's picture CLOSE UP: the whole screen, cut from the
top of ui/zero/zero.jpg at the screen's own 4:3, head to chest. Shown
whole she was a 158px strip down the middle of black; her page shows
her full height only because the conversation log takes the rest of
the screen, and the cube has no log. Rendered both ways at 320x240 and
looked at. Her picture is a whole illustration with its own dark room
(ui/zero/ART.txt), so a crop is framing, not surgery -- no alpha.

GENERATED, AND COMMITTED ANYWAY, the Modelfile call: flashing the cube
must not need PIL on whatever machine does it, and a test regenerates
these into memory and compares, so a header cannot drift from her art.
Change a picture, run this, commit both.

WORKBENCH TOOL. PIL is needed here and nowhere else -- the deck never
imports this, same standing as yuzu_art.py.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
UI = HERE.parent / "ui"
SOURCE = UI / "four" / "four.jpg"
OUT = HERE / "cube" / "four_art.h"
ART_W, ART_H = 160, 240

YUZU_SOURCE = UI / "yuzu" / "yuzu.png"
YUZU_OUT = HERE / "cube" / "yuzu_art.h"
YUZU_W, YUZU_H = 178, 230
ZERO_SOURCE = UI / "zero" / "zero.jpg"
ZERO_OUT = HERE / "cube" / "zero_art.h"
ZERO_W, ZERO_H = 320, 240
ZERO_TOP = 60          # source pixels skipped above her head
# Her page's mask: linear-gradient(to bottom, #000 84%, transparent) and
# linear-gradient(to right, transparent, #000 9%, #000 91%, transparent).
FADE_BOTTOM, FADE_SIDE = 0.16, 0.09


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def _array(lines, ctype, name, values, fmt):
    lines.append("static const %s %s[%d] = {" % (ctype, name, len(values)))
    for i in range(0, len(values), 16):
        lines.append("  " + ",".join(fmt % v for v in values[i:i + 16]) + ",")
    lines.append("};")


def render(source=SOURCE):
    """four_art.h's text. Same input, same bytes, every time."""
    from PIL import Image
    img = Image.open(source).convert("RGB").resize((ART_W, ART_H),
                                                     Image.LANCZOS)
    px = img.load()
    values = [rgb565(*px[x, y]) for y in range(ART_H) for x in range(ART_W)]
    lines = ["// GENERATED by stackchan/make_art.py from ui/four/four.jpg.",
             "// Do not edit -- change her picture and run the script.",
             "#pragma once",
             "#include <stdint.h>",
             "static const int FOUR_ART_W = %d, FOUR_ART_H = %d;"
             % (ART_W, ART_H),
             "// RGB565, row by row, as the colour (not byte-swapped)."]
    _array(lines, "uint16_t", "FOUR_ART", values, "0x%04x")
    return "\n".join(lines) + "\n"


def _fade(x, y):
    """Her page's mask at one pixel, 0..1."""
    edge_y = (YUZU_H - 0.5 - y) / (FADE_BOTTOM * YUZU_H)
    edge_x = min(x + 0.5, YUZU_W - 0.5 - x) / (FADE_SIDE * YUZU_W)
    return max(0.0, min(1.0, edge_y)) * max(0.0, min(1.0, edge_x))


def render_yuzu(source=YUZU_SOURCE):
    """yuzu_art.h's text: her colour as RGB565 and her alpha, 0..255."""
    from PIL import Image
    # Shrunk with her alpha PREMULTIPLIED ("RGBa"), or the cut-out's
    # white edge bleeds into her outline as a pale halo.
    img = (Image.open(source).convert("RGBA").convert("RGBa")
           .resize((YUZU_W, YUZU_H), Image.LANCZOS).convert("RGBA"))
    px = img.load()
    colour, alpha = [], []
    for y in range(YUZU_H):
        for x in range(YUZU_W):
            r, g, b, a = px[x, y]
            a = int(round(a * _fade(x, y)))
            colour.append(rgb565(r, g, b) if a else 0)
            alpha.append(a)
    lines = ["// GENERATED by stackchan/make_art.py from ui/yuzu/yuzu.png.",
             "// Do not edit -- change her picture and run the script.",
             "#pragma once",
             "#include <stdint.h>",
             "static const int YUZU_ART_W = %d, YUZU_ART_H = %d;"
             % (YUZU_W, YUZU_H),
             "// RGB565, row by row, as the colour (not byte-swapped), and",
             "// her alpha with her page's fades already in it."]
    _array(lines, "uint16_t", "YUZU_ART", colour, "0x%04x")
    _array(lines, "uint8_t", "YUZU_ALPHA", alpha, "%d")
    return "\n".join(lines) + "\n"


def render_zero(source=ZERO_SOURCE):
    """zero_art.h's text: the whole screen, RGB565."""
    from PIL import Image
    img = Image.open(source).convert("RGB")
    tall = img.width * ZERO_H // ZERO_W
    img = img.crop((0, ZERO_TOP, img.width, ZERO_TOP + tall)).resize(
        (ZERO_W, ZERO_H), Image.LANCZOS)
    px = img.load()
    values = [rgb565(*px[x, y]) for y in range(ZERO_H) for x in range(ZERO_W)]
    lines = ["// GENERATED by stackchan/make_art.py from ui/zero/zero.jpg.",
             "// Do not edit -- change her picture and run the script.",
             "#pragma once",
             "#include <stdint.h>",
             "static const int ZERO_ART_W = %d, ZERO_ART_H = %d;"
             % (ZERO_W, ZERO_H),
             "// RGB565, row by row, as the colour (not byte-swapped)."]
    _array(lines, "uint16_t", "ZERO_ART", values, "0x%04x")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    try:
        texts = [(OUT, render()), (YUZU_OUT, render_yuzu()),
                 (ZERO_OUT, render_zero())]
    except ImportError:
        sys.exit("This needs PIL: pip install pillow. The committed "
                 "headers already work; you only need this to change a "
                 "picture.")
    for path, text in texts:
        path.write_text(text)
        print("wrote %s (%d bytes)" % (path, len(text)))
